### ISSUE TITLE
Add map labels above data visualization layer

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#30]
From EJ: _Is there functionality to add the administrative labels above the visualization layer? It gets hard to read and given that you want this oriented toward a national audience they’re not going to know the local names without clicking and it would be better to put above the viz._

**Comment by Makosak** [comment]
This is the layer I've used for adding labels only on top -- it adjusts by zoom automatically. If someone wants to tool around with seeing how compatible it would be to add?

Provider names for leaflet-providers.js
CartoDB.PositronOnlyLabels
Plain JavaScript:
var CartoDB_PositronOnlyLabels = L.tileLayer('https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}{r}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
      subdomains: 'abcd',
      maxZoom: 19
});

via https://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by Makosak** [comment]
@rbrtmrtn  this will be the feature we talked about; you would see if the Mapbox label layering works instead since the overlay doesn't worth? https://blog.mapbox.com/labels-on-top-fad3dab3bc8

**Comment by ariisrael** [comment]
Deck.gl renders on top of Mapbox, and we can only get the labels to the top of the Mapbox map. So we need to remove Deck.gl (which we should, we aren't really using it) and then this should be easy.

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#30: Add label layer above geo layer](https://trello.com/c/AZvmyY5p/102-30-add-label-layer-above-geo-layer)

**Comment by rbrtmrtn** [comment]
Hello @lixun910! Glad to be working on this issue together this week :) 

I wanted to touch base here to see what your thoughts were on rendering map labels above the visualization layers. I'm familiar with this MapboxGL recipe for adding a layer below the labels layer:

https://docs.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/

...however, since Deck.gl seems to render a WebGL canvas _on top_ of the Mapbox container, I'm not sure how we will be able to stack a layer of labels on top of that. I think you may be more familiar with Deck than I am. Did you have any thoughts on how we might be able to accomplish this?

Thanks and looking forward to getting your insights!

**Comment by rbrtmrtn** [comment]
Hello again @lixun910!

Thank you for the suggestion to take a look at this Deck.gl label rendering example: https://deck.gl/gallery/text-layer

I noticed that example requires a JSON file of map labels. Personally, I'm not familiar with any JSON sets of administrative labels that would fit this spec 🤔  If you have any suggestions I'm happy to experiment.

Normally I would rely on the labels that Mapbox itself provides, but as I mentioned above these will be unavailable since Deck.gl is rendering a WebGL canvas on top of Mapbox, and that will obscure the labels.

I know that in the past @Makosak has suggested using the Carto labels layer from this gallery of Leaflet basemap demos: https://leaflet-extras.github.io/leaflet-providers/preview/

We can do that if that seems like a good fit! Even though they're raster tiles, we should be able to shim them into MapboxGL, does that sound about right?

Thanks everyone!!

**Comment by lixun910** [comment]
Yes, it ‘a worth a quick try!

**Comment by rbrtmrtn** [comment]
I'm using this documentation

https://github.com/visgl/deck.gl/blob/master/docs/layers/tile-layer.md

to add a `TileLayer` (with an embedded `BitmapLayer`) to the top of the map stack with the Carto map labels. I've followed the instructions closely (as far as I can tell) and am getting this error:

```
Uncaught TypeError: Cannot read property 'visible' of undefined
    at dist.min.js:11
```

This is my code:

```
layers.push(new TileLayer({
      id: 'map-labels',
      data: [
        'https://a.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png',
        'https://b.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png',
        'https://c.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png',
      ],
      renderSubLayers: async (props) => {
        const {
          bbox: { west, south, east, north }
        } = props.tile;

        return new BitmapLayer(props, {
          data: null,
          image: props.data,
          bounds: [west, south, east, north],
        });
      },
    }));
```

I'm not sure what's going wrong. I've Googled this without any results. The documentation for Deck.gl is very limited and out of date. We're using a minified/production bundle of Deck.gl which doesn't support debugging; I've tried removing `.min` from the URL to get a more intact bundle but it doesn't exist. I think this task may have to wait until we can switch to using MapboxGL directly, unless you see something that I'm missing here @lixun910. Thanks!
