### ISSUE TITLE
Add Search bar 

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#48]
Add search bar so users can enter address or place and have the map zoom accordingly.

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#48: Add Search bar](https://trello.com/c/n0V3eLqt/96-48-add-search-bar)

**Comment by rbrtmrtn** [comment]
Hello @lixun910! Happy to be working on this together this week. Based on @Makosak's comment above, it sounds like we've chosen Mapbox as a geocoding/search provider. I can get started on adding the search control, which is usually not hard to add to a typical MapboxGL instance. The only decision point here is that it's normally added to one of the four corners of the map, which are currently occupied by our app. I'll try to think of a place to put it, or if you have other thoughts feel free to let me know! Thank you!

**Comment by Makosak** [comment]
It doesn't have to be Mapbox -- this was just the comment after we had a meeting about it earlier that the group decided to use Mapbox. Editing the comment, whatever technology works is fine.

**Comment by rbrtmrtn** [comment]
I think Mapbox is a great choice! Happy to stick with that direction, thanks @Makosak!

**Comment by lixun910** [comment]
I am working on other things now and will work on this later this week. FYI: the old code has some functions to render labels for LISA clusters by following the example here: https://deck.gl/gallery/text-layer

**Comment by rbrtmrtn** [comment]
Thank you @lixun910, this is the geocoding issue but I'll go ahead and follow up with you re: labels on the label issue (#30)!

**Comment by lixun910** [comment]
For mapbox, there is an interface/handle for mapbox via deck.gl (check the code re. zoom button, which is actually mapbox navigation controller). Keep in mind that the underneath basemap is still mapbox, deck.gl is a higher-level library that is designed to work with other basemaps as well.

**Comment by rbrtmrtn** [comment]
Thanks @lixun910, once again I will follow up on the labels issue (#30)!

**Comment by rbrtmrtn** [comment]
Hey @lixun910, just wanted to follow up that I have a draft of the Atlas with the search bar added. It's pushed up here on the `search` branch. There's also a live demo here:

https://5ed5e810ec7ef970f277e47c--covid-atlas-alpha.netlify.app/map.html

Note that there's a bug where the first time you search it will take you to the correct location, but quickly pan to somewhere near Santa Fe, NM (for me at least; might be different depending on your screen/viewport). After that first search it works OK. 

Obviously this is a blocking bug, but I don't think it has to do with the search. The same thing happens for me if I just load the app fresh and open the Chrome DevTools panel. It will pan to that same location (this has been the case since before search was added).

Feel free to let me know what you think of this draft and if you have any comments and/or insight into that strange bug! Thanks!

**Comment by rbrtmrtn** [comment]
I was able to fix the bug where the map would zoom to the wrong location on search (see #89, #90). I was hoping this would unblock the search bar work without having to take on the bigger task of swapping out Deck entirely, however I'm now running into an issue where the map zooms correctly on search but Deck.gl doesn't repaint the data viz layer; for example this is what happens when I search for Chicago:

![image](https://user-images.githubusercontent.com/1463553/83696525-49e1e180-a5c2-11ea-9a6a-97fcbd3aedb6.png)

I think we're at a decision point where we can either continue to try to fold Mapbox features/functionality into Deck, or invest time into removing Deck from the code base. Removing Deck is a better long-term solution IMO, but it may also mean that that's our only deliverable for this week. I can certainly try to get the labels task (#30) done as well, but I may have to check in with more updates later in the week based on how the Mapbox migration is going. I wanted to check in with you @lixun910 @Makosak about this and make sure this aligns with our priorities right now. I hope I've explained the challenges/blockers here well enough but please feel free to follow up with any questions.
